# Generated by Django 4.1.2 on 2022-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_path',
            new_name='image',
        ),
    ]
